apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todoserver-dep
  namespace: project-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoserver
  strategy:
    canary:
        analysis:
          templates:
          - templateName: cpu-rate
        steps:
          - setWeight: 25
          - pause:
              duration: 30s
          - setWeight: 50
          - pause:
              duration: 30s
  template:
    metadata:
      labels:
        app: todoserver
    spec:
      containers:
      - name: todoserver
        image: IMAGE_PLACEHOLDER
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          httpGet:
            path: /ready
            port: 9000
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          httpGet:
            path: /live
            port: 9000
        env:
          - name: NATS_URL
            value: nats://my-nats.default:4222
        envFrom:
          - secretRef:
              name: pg-secret
        resources:
          limits:
            cpu: "250m"
            memory: "100Mi"