apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - backend/manifests/deployment.yaml
 - backend/manifests/service.yaml

 - frontend/manifests/deployment.yaml
 - frontend/manifests/service.yaml