apiVersion: apps/v1
kind: Deployment
metadata:
  name: todofrontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todofrontend
  template:
    metadata:
      labels:
        app: todofrontend
    spec:
      containers:
      - name: todofrontend
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          limits:
            cpu: "250m"
            memory: "100Mi"