apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps-ns
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: logoutput-config
          configMap:
            name: logoutput-dotenv
            items:
              - key: ".env"
                path: ".env"
      containers:
        - name: logoutput
          image: pndy/logoutput:2.06
          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/files
            - name: logoutput-config
              mountPath: /usr/src/app/.env
              subPath: .env
              readOnly: true
          env:
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: service-apikey
                  key: API_KEY
        - name: loggenerator
          image: pndy/loggenerator:1.13
          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/files