apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: service-apikey
  namespace: apps-ns
spec:
  encryptedData:
    API_KEY: AgB4tzQndJGBlnDcz6221DM0sq5xWYKaz2FHCtMO9DPktRtDvUv0MM7tjSirBpcjW4cT5SR/Ylu9nQvuiWCFUqrxeZEPVCT1YrgBwypNa3d1uNdCSLN5JmBvtD4/Pd/K9fDJdEWNgS/OHLFetVK0++8BWUqxeULW2+fWXfBbwjWOUfJU6eXGgwR8qbqlFHD09fNsGKfhLEM18QunCZ9napLwofgajdLegtiTsrICNoX/1M1PHMFWQc2+HpKqLdPB2kSsy3fnTxAjkIE2K4AJryNi14HLtTrCCnep9984GC6EnSk58ZHmxcqkOmd9IONoLiIxBouUIgW7KRNIOXUE9y4siCtT9mqkdPOBb9kede7PrIorgI5BSd356ScEaxKlzZNuH5TxzW8hcEX9BVPeQ0hagwMD35wnZnA+wDtqgeck1fHM5SIM+FwsR860UiuT/jYbCn1/6uQLRhdp7MsQ4NPzwm+jfvqMgyzsmYHUSOwcQDZrxsVuZ/vW+2ELuzmjn2167PDSBE+pZjSI8aTOJLjGDAHIsocrnsaQE0UpREoivW1uCviKV9469QamMxrEkry7TIQLMEe3GtP+hSFKGXpYg7QtCTgTUwDxPJMVKTsMRd0yU/GseKt7/ssJaQ3dRCuDh/ajFlYOaSPTtv9aQMaeZxptQkWx5XE5cz1IDQZqcaNCH9n+B+lPGdhnTo07Ft6ZelkK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: service-apikey
      namespace: apps-ns

