apiVersion: ENC[AES256_GCM,data:vyI=,iv:GfK1nVVbv5oVEwCsXuW/Ukpv8MrYjeSEt8IskreBRxk=,tag:CCHyM0et6gQR9Moe4z3saA==,type:str]
kind: ENC[AES256_GCM,data:Y1sJILTT,iv:FtmqZ7/UC/EjCL4zTVcWEty2QCIufxFkiA4oE4QWiLY=,tag:nK8yPOthCsU61X3LNvvlSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pVXtZw9PJKKPH6hBpbs=,iv:hBUDl3g56h3OVCNcjvLtcMPywVqwEAV26I8wBHBMVRI=,tag:5U9NK04xUcpV70TzBHONww==,type:str]
    namespace: ENC[AES256_GCM,data:LVaUB0YxNQ==,iv:VoxFdF4zQVublYWk14HOxGCEBuHgOEVQVS5RROYjBL4=,tag:Fok1zD4PKgQjCJBL+QwAjw==,type:str]
type: ENC[AES256_GCM,data:3TtozPNV,iv:a36hcRIxJB5L5Um9HuCcHXVBU1tdMorsAlJfdTd3ASI=,tag:zumg42pbYemO7iNHqRsxCw==,type:str]
data:
    password: ENC[AES256_GCM,data:jyqrrDqaBmw=,iv:0P3qOLoiO2ryvDq1avvVVEgiOCeiOF8NXbxwtEbX3C8=,tag:FKTiBWiY1DnEf8putEUpXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tuscuex0jsh2xevu6fknq24uvdlk06zp0g7ql5atnjqlgnhrx4asn4errc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWnlpWXF2SkNUazl3b2lp
            Tk42elVNSjhxWjYrM2VraWF3RWtWNXVWZzBvClBCdC9MYXBQNUVUR2lQNEI0b2J5
            dUJRaWV6cVZVTXRaSkFyNk1HN1JaYmcKLS0tIGk1UEFuUHdoZ21YRmdIT3EzN3o3
            QnRSeWFQVXhzRHpBd0VtL0UwTGdUTVUKz0yDiv4Fg8vqc1W7WO5WMPDDRyfU8hcI
            Ni3881kLN7LnpgCr5bJrcG+WVNRw2wqhhMP154tPgKRETdpBEaNwIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-12T21:56:23Z"
    mac: ENC[AES256_GCM,data:swvKSHO2D5hJXwSePt6CDEr3fUAdOlfZJdpeRuz5g8eiriNfRzSghgH/c/Ii6+rPMwEJT6+9hfX4fJ/MaFTCaMB9/m/1JEOXtUWLkOYEeDsmF4xOPO/+hULgBIFK8TgKH2IpDl8/fj1y09ytAHH9+QI1KN3TAmZKwLUSlRCOAXk=,iv:XWiSQnrvWH7Gv756nhpSUmtf5bXeyk8z3SNQEJXP0Cw=,tag:KTKfA97aNC/Vw+BYRWLpfw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
