apiVersion: ENC[AES256_GCM,data:pYA=,iv:wGjV4KOO0cROkkJhJW5Tp7tTh5Xru+s8eeitadYJWXI=,tag:nDg2oUDl/Ekz6qr4rf4pvw==,type:str]
kind: ENC[AES256_GCM,data:4W7upl+O,iv:M7CKGS2y0AXVeYow2O2sqA4LK+O1QUpJcIaRUfD+zuE=,tag:R6EnenAY9pMbyGDhd6sWww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:m27SoRc/kDPiv0lONfY=,iv:xLFrTMj+YngzOgApcrjD6VClbKYs4flHtBJBzsqinM0=,tag:zx0bJmB8mie2acjLq408/w==,type:str]
    namespace: ENC[AES256_GCM,data:osvygDa+xg==,iv:xoW+30JsDDtM/7ztaeAF0B8NkCa0G3aP7PhhalfHelc=,tag:jb5Vdf5y37aIIdXU7FeB0Q==,type:str]
type: ENC[AES256_GCM,data:Lh8ogtdt,iv:vrHu5tlUWL+5i0bJnelg+K3RhyLKBJFRqohqB7HEc6o=,tag:krWQBNfqc0jk6pwBKlFchw==,type:str]
data:
    API_KEY: ENC[AES256_GCM,data:4bR9sS97FqA=,iv:SA1vaJxb/BZhKJ5pDs8enhYpyxY88pPL/0LE+cLwnP0=,tag:i3HK15hKsj8Ts0mxlWpZoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tuscuex0jsh2xevu6fknq24uvdlk06zp0g7ql5atnjqlgnhrx4asn4errc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSEhwMVd3c2tyOHh4bFRQ
            OXNCTWdIb1lMK1hLNmw5VmgzTEFXRlFPZkNnClozY0ZhdzdHMHVWR2pwUUdqWU5C
            NWlkTkhNejIraVp3TG16VlAwODhkY2sKLS0tIHd2ZkJsTGZrT0pGbHBIZVMweDUy
            NE1kc2ZHVVE5WCs1NGR2L0d1VUJxbTAKvOczC7V6NWPdo+jG3qqtdsWNp8+Yiwzv
            R4deLD0I0giV266k5snAlayLypf7YkPyJKPtHHR6hFUEziXVJ15gcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-14T13:01:59Z"
    mac: ENC[AES256_GCM,data:66PmoxF9bbjQ+ZaEnOcFSCpSyxq6i4QRgLwCOQCrdyz+50GdgMjQPXanYkTZrY2HteGnXgZyO8j9jnRUKBU+Z0eGcOyrtFmzYI6GVjpegfmOkjNi03VoOkPTB+hulvtgEtvJ7cEehqbYzm1VSR0RLWPNZmg+W1lsWs47BCFABjk=,iv:kTYE8ZB3z0we1tRXuWP6PiMOua4qQHjatVGpUBN32tg=,tag:uD6Px/cXqMLI1i0HteEl+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
