apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: project-ns
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 10m
    successCondition: result < 0.1
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-stack-1638-prometheus-0.prometheus.svc.cluster.local:9090
        query: sum(rate(container_cpu_usage_seconds_total{namespace="project-ns"}[10m]))