apiVersion: apps/v1
kind: Deployment
metadata:
  name: todofrontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todofrontend
  template:
    metadata:
      labels:
        app: todofrontend
    spec:
      containers:
      - name: todofrontend
        image: pndy/todofrontend:2.02.1