apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todofrontend-dep
  namespace: project-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todofrontend
  strategy:
    canary:
        analysis:
          templates:
          - templateName: cpu-rate
        steps:
          - setWeight: 25
          - pause:
              duration: 30s
          - setWeight: 50
          - pause:
              duration: 30s
  template:
    metadata:
      labels:
        app: todofrontend
    spec:
      containers:
      - name: todofrontend
        image: pndy/todofrontend:4.4.4
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          httpGet:
            path: /api/todos
            port: 3000
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          httpGet:
            path: /api/todos
            port: 3000
        resources:
          limits:
            cpu: "250m"
            memory: "100Mi"