apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: shared-pings
          persistentVolumeClaim:
            claimName: logapps-claim
      containers:
        - name: logoutput
          image: pndy/logoutput:1.11.1
          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/files
            - name: shared-pings
              mountPath: /usr/src/app/pings
        - name: loggenerator
          image: pndy/loggenerator:1.13
          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/files