apiVersion: batch/v1
kind: CronJob
metadata:
  name: dailytodo-cronjob
  namespace: project-ns
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dailytodo
            image: pndy/dailytodo:2.09.1
            envFrom:
            - secretRef:
                name: pg-secret
          restartPolicy: OnFailure
