apiVersion: ENC[AES256_GCM,data:Ml8=,iv:s6zFq1GXSvga31FADJL37atSHZ7a91Cs+3wIGmLAMA4=,tag:teYuqr71QhV2I1FOgD0sLg==,type:str]
kind: ENC[AES256_GCM,data:rK2f9pIy,iv:ZhZPAHTQj8YFNeSue/XQBRUUsrcMyqQCKSYqoIleuyI=,tag:Pj5X5//bBW46qWosHbry7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VeQ1OrcyTbOrLzrqzwc=,iv:6QvrxcIcXa+f0U1bS5bEaQyEKmTxMSkeGBSaz/K+kBI=,tag:3PaycjvURlU5/z94lAjf7A==,type:str]
data:
    password: ENC[AES256_GCM,data:o0mXavwyqls=,iv:LAdZBS+WHyfgR+BP/NOrfrw7/fUvER/p5FxOEIMfSYc=,tag:fWuD4OOldpy51S1jAsjc1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d3fqzke08cekuhnt88dddrrhskf3wrch5t2ql4scd5xccz4m6sgqzagp0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV1VBdG9IZUViWDFYY1dN
            d0VZTFIxS0ROUmVSNWZhNWJSeU9HV25hTlQ4CmdtTmxTcEhDdXdVOUhNbCtMYWla
            S2o5Tm54dmt4Z2RtR1JNR2c4S0FSRUUKLS0tIHBRb3c4MWZMNkNHRXVqVXByVzBD
            WFlETytEU0sxdkxSUU5DQWRLWExrQXMKtOtiU/CTiwuvzIAIp1cEtWKVNAXTm/RH
            GPRnJ1jIoaGzrqXDvjUvhzH2yV9iW71v1u6GIu+BhyboaePcLZuf0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-03T20:53:30Z"
    mac: ENC[AES256_GCM,data:NVCLiB+OGc2ihc/sHl6D1CahD8Iiw7tAraTA3Q+IVgIV0W++dD1sD1HbTH2qS7Of3to/dM2N7pYq0/Us/Z3ScRzuBmZngbOZXOFF9dAZ+NS+mwYGalnzmj6Dk/0aqHe6ZFO6+D22GzFw6jWQwW66Te8TQsMC9xUKGi/RF/PlFGo=,iv:Om66/jpT0TDHiyj4dfWiEYnPIrBxMuN9tPvrcZlPBSE=,tag:hlwhywNCsDnk5elQ2jadqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
