apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: apps-ns
  name: logapps-claim
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce