apiVersion: v1
kind: Service
metadata:
  namespace: project-ns
  name: todoserver-svc
spec:
  type: ClusterIP
  selector:
    app: todoserver
  ports:
  - port: 1234
    targetPort: 3000
    protocol: TCP