name: Part 4 GitOps

on:
  push:
    branches:
     - main
    paths:
     - 'part4/todoapp/backend/**'
     - '.github/workflows/gitops.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: part4/todoapp/backend
        push: true
        tags: pndy/todoserver:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Setting up Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Update kustomize yaml
      working-directory: part4/todoapp/backend
      run: |-
        kustomize edit set image IMAGE_PLACEHOLDER=pndy/todoserver:${{ github.sha }}

    - uses: EndBug/add-and-commit@v7
      with:
        add: 'part4/todoapp/backend/kustomization.yaml'
        message: new update to backend ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}